<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BitacoraLiberacionUnidadesElectrico extends Model
{
    protected $connection = 'mysql';
    protected $table = 'bitacora_liberacion_unidades_electrico';
    protected $primaryKey = 'id_bitacora'; // Si la tabla tiene una clave primaria distinta a 'id', ajústala aquí

    protected $fillable = [
        'n_economico',
        'fecha_hora',
        'n_mecanico',
        'n_supervisor',
        'fecha',
        'km',
        'luc_ext_ilu_fron_far_izq',
        'luc_ext_ilu_fron_far_izq_o',
        'luc_ext_ilu_fron_luc_baj_izq',
        'luc_ext_ilu_fron_luc_baj_izq_o',
        'luc_ext_ilu_fron_luc_alt_izq',
        'luc_ext_ilu_fron_luc_alt_izq_o',
        'luc_ext_ilu_fron_inter_izq',
        'luc_ext_ilu_fron_inter_izq_o',
        'luc_ext_ilu_fron_torr_izq',
        'luc_ext_ilu_fron_torr_izq_o',
        'luc_ext_ilu_fron_estro_izq',
        'luc_ext_ilu_fron_estro_izq_o',
        'luc_ext_ilu_fron_nebl_izq',
        'luc_ext_ilu_fron_nebl_izq_o',
        'luc_ext_ilu_fron_plaf_izq',
        'luc_ext_ilu_fron_plaf_izq_o',
        'luc_ext_ilu_fron_sopor_faro_izq',
        'luc_ext_ilu_fron_sopor_faro_izq_o',
        'luc_ext_ilu_fron_far_der',
        'luc_ext_ilu_fron_far_der_o',
        'luc_ext_ilu_fron_luc_baj_der',
        'luc_ext_ilu_fron_luc_baj_der_o',
        'luc_ext_ilu_fron_luc_alt_der',
        'luc_ext_ilu_fron_luc_alt_der_o',
        'luc_ext_ilu_fron_inter_der',
        'luc_ext_ilu_fron_inter_der_o',
        'luc_ext_ilu_fron_torr_der',
        'luc_ext_ilu_fron_torr_der_o',
        'luc_ext_ilu_fron_estro_der',
        'luc_ext_ilu_fron_estro_der_o',
        'luc_ext_ilu_fron_nebl_der',
        'luc_ext_ilu_fron_nebl_der_o',
        'luc_ext_ilu_fron_plaf_der',
        'luc_ext_ilu_fron_plaf_der_o',
        'luc_ext_ilu_fron_sopor_faro_der',
        'luc_ext_ilu_fron_sopor_faro_der_o',
        'lat_pri_carr_plaf_inf_izq',
        'lat_pri_carr_plaf_inf_izq_o',
        'lat_pri_carr_plaf_inf_der',
        'lat_pri_carr_plaf_inf_der_o',
        'lat_pri_carr_plaf_sup_izq',
        'lat_pri_carr_plaf_sup_izq_o',
        'lat_pri_carr_plaf_sup_der',
        'lat_pri_carr_plaf_sup_der_o',
        'lat_seg_carr_plaf_inf_izq',
        'lat_seg_carr_plaf_inf_izq_o',
        'lat_seg_carr_plaf_inf_der',
        'lat_seg_carr_plaf_inf_der_o',
        'lat_seg_carr_plaf_sup_izq',
        'lat_seg_carr_plaf_sup_izq_o',
        'lat_seg_carr_plaf_sup_der',
        'lat_seg_carr_plaf_sup_der_o',
        'ilu_tras_cala_izq',
        'ilu_tras_cala_izq_o',
        'ilu_tras_cala_der',
        'ilu_tras_cala_der_o',
        'ilu_tras_stop_izq',
        'ilu_tras_stop_izq_o',
        'ilu_tras_stop_der',
        'ilu_tras_stop_der_o',
        'ilu_tras_rever_izq',
        'ilu_tras_rever_izq_o',
        'ilu_tras_rever_der',
        'ilu_tras_rever_der_o',
        'ilu_tras_inter_izq',
        'ilu_tras_inter_izq_o',
        'ilu_tras_inter_der',
        'ilu_tras_inter_der_o',
        'ilu_tras_sop_cala_izq',
        'ilu_tras_sop_cala_izq_o',
        'ilu_tras_sop_cala_der',
        'ilu_tras_sop_cala_der_o',
        'luc_int_luc_cond',
        'luc_int_luc_cond_o',
        'luc_int_letr_rut',
        'luc_int_letr_rut_o',
        'luc_int_letr_5_seg',
        'luc_int_letr_5_seg_o',
        'luc_int_luc_puer',
        'luc_int_luc_puer_o',
        'luc_pasi_pri_carr_pri_paso_izq',
        'luc_pasi_pri_carr_pri_paso_izq_o',
        'luc_pasi_pri_carr_pri_paso_der',
        'luc_pasi_pri_carr_pri_paso_der_o',
        'luc_pasi_pri_carr_seg_paso_izq',
        'luc_pasi_pri_carr_seg_paso_izq_o',
        'luc_pasi_pri_carr_seg_paso_der',
        'luc_pasi_pri_carr_seg_paso_der_o',
        'luc_pasi_seg_carr_pri_paso_izq',
        'luc_pasi_seg_carr_pri_paso_izq_o',
        'luc_pasi_seg_carr_pri_paso_der',
        'luc_pasi_seg_carr_pri_paso_der_o',
        'luc_pasi_seg_carr_seg_paso_izq',
        'luc_pasi_seg_carr_seg_paso_izq_o',
        'luc_pasi_seg_carr_seg_paso_der',
        'luc_pasi_seg_carr_seg_paso_der_o',
        'alin_alin_luc_baj_izq',
        'alin_alin_luc_baj_izq_o',
        'alin_alin_luc_baj_der',
        'alin_alin_luc_baj_der_o',
        'alin_alin_luc_alt_izq',
        'alin_alin_luc_alt_izq_o',
        'alin_alin_luc_alt_der',
        'alin_alin_luc_alt_der_o',
        'alin_alin_luc_neb_izq',
        'alin_alin_luc_neb_izq_o',
        'alin_alin_luc_neb_der',
        'alin_alin_luc_neb_der_o',
        'inte_inte_luc_baj_izq',
        'inte_inte_luc_baj_izq_o',
        'inte_inte_luc_baj_der',
        'inte_inte_luc_baj_der_o',
        'inte_inte_luc_alt_izq',
        'inte_inte_luc_alt_izq_o',
        'inte_inte_luc_alt_der',
        'inte_inte_luc_alt_der_o',
        'inte_inte_nebl_izq',
        'inte_inte_nebl_izq_o',
        'inte_inte_nebl_der',
        'inte_inte_nebl_der_o',
        
    ];

    // Si no se van a utilizar los campos created_at y updated_at, ajusta las siguientes propiedades:
    public $timestamps = false;
}
